# replace categorie to define the default model covered by this document, first letter must be uppercase
# replace categorie to define the default path of endpoints in this document, first letter must be lowercase
# add missing endpoints
# N.B. : must then be added to the pom to generate the controller and its associated models

openapi: 3.0.0
info:
  title: Catégorie API
  version: '0.0.1'
paths:
  /categories:
    get:
      tags:
        - Categorie
      summary: 'all categories'
      operationId: findAll
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorieOpenApiModel'
components:
  schemas:
    'CategorieOpenApiModel':
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
          maxLength: 75

    Error:
      description: format message for error return HTTP
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string