# replace film to define the default model covered by this document, first letter must be uppercase
# replace film to define the default path of endpoints in this document, first letter must be lowercase
# add missing endpoints
# N.B. : must then be added to the pom to generate the controller and its associated models

openapi: '3.0.0'
info:
  description: 'Film API'
  version: '0.0.1'
  title: 'OpenAPI Film'
tags:
  - name: Film
    description: ''

paths:
  /film:
    get:
      tags:
        - Film
      summary: 'all Films'
      operationId: findAll
      responses:
        '200':
           description: 'OK'
           content:
              application/json:
                schema:
                  type: array
                  items:
                      $ref: '#/components/schemas/FilmOpenApiModel'


        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:
    'FilmOpenApiModel':
      description: 'Object representing a currently accessible ressource'
      type: object
      required:
          - titre
          - duree
          - realisateur
          - description
          - photo
          - dateSortie
          - categorieId
      properties:
        id:
          type: integer
          format: int64
        titre:
          type: string
        duree:
          type: number
          format: double
        realisateur:
          type: string
        description:
          type: string
        photo:
          type: string
        dateSortie:
          type: string
          format: date-time
        categorieId:
          type: integer
          format: int64

    Error:
      description: format message for error return HTTP
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string






