# replace salle to define the default model covered by this document, first letter must be uppercase
# replace salle to define the default path of endpoints in this document, first letter must be lowercase
# add missing endpoints
# N.B. : must then be added to the pom to generate the controller and its associated models

openapi: '3.0.0'
info:
  description: 'Salle API'
  version: '0.0.1'
  title: 'OpenAPI Salle'
tags:
  - name: Salle
paths:
  /salle:
    get:
      tags:
        - Salle
      summary: 'all Salles'
      operationId: findAll
      responses:
        '200':
           description: 'OK'
           content:
              application/json:
                schema:
                  type: array
                  items:
                      $ref: '#/components/schemas/SalleOpenApiModel'
    post:
      tags:
        - Salle
      summary: 'create new salle'
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalleOpenApiModel'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalleOpenApiModel'
    put:
      tags:
        - Salle
      summary: 'Update existing salle'
      operationId: update
      requestBody:
        description: 'Update existing salle'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalleOpenApiModel'

      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalleOpenApiModel'

        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /salle/{id}:
    get:
      tags:
        - Salle
      summary: 'Specific Salle'
      operationId: findOne
      parameters:
        - name: id
          in: path
          description: 'Find a Salle by its id'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalleOpenApiModel'
        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Salle
      summary: 'delete a salle'
      operationId: delete
      parameters:
        - name: id
          in: path
          description: 'Find a Salle by its id'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: DELETED
        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    'SalleOpenApiModel':
      description: 'Object representing a currently accessible ressource'
      type: object
      required:
          - name
          - nombrePlaces
          - places
          - filmProjections
          - cinema
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nombrePlaces:
          type: integer
        places:
          type: array
          items:
            $ref: '#/components/schemas/PlaceOpenApiModel'
        filmProjections:
          type: array
          items:
            $ref: '#/components/schemas/FilmProjectionOpenApiModel'
        cinema:
          $ref: '#/components/schemas/CinemaOpenApiModel'


    'PlaceOpenApiModel':
      description: 'Object representing a currently accessible ressource'
      type: object
      required:
        - numero
      properties:
        id:
          type: integer
          format: int64
        numero:
          type: integer

    'FilmProjectionOpenApiModel':
      description: 'Object representing a currently accessible ressource'
      type: object
      required:
        - dateProjection
        - prix
      properties:
        id:
          type: integer
          format: int64
        dateProjection:
          type: string
          format: date-time
        prix:
          type: number
          format: double

    'CinemaOpenApiModel':
      description: 'Object representing a currently accessible ressource'
      type: object
      required:
        - name
        - longitude
        - latitude
        - altitude
        - nombreSalles
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        altitude:
          type: number
          format: double
        nombreSalles:
          type: integer

    Error:
      description: 'format message for error return HTTP'
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string






